[versions]
querydsl = "5.1.0"

[libraries]
querydsl = { module = "com.querydsl:querydsl-jpa", version.ref = "querydsl" }
querydsl-apt = { module = "com.querydsl:querydsl-apt", version.ref = "querydsl" }

[plugins]
